spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ASTON
    password: test
    driver-class-name: org.postgresql.Driver
    username: postgres
  jpa:
    show-sql: on
logging:
  level:
    root: warn